### ISSUE TITLE
Fix GeoJSON constructor

### ISSUE THREAD

**Issue by lionetxue** [bbarker/scalajs-mapbox#2]
Should [take 2 params](https://github.com/Leaflet/Leaflet/blob/a3425850ca47969487ea0c0db153d90f16492397/src/layer/GeoJSON.js):

``` javascript
L.GeoJSON = L.FeatureGroup.extend({

    initialize: function (geojson, options) {
        L.setOptions(this, options);
```

But currently only takes 1:

``` scala
@JSName("L.GeoJSON")
class GeoJSON(options: js.Object = null) extends FeatureGroup {
```

**Comment by bbarker** [comment]
Created temporary solution, but may want to create an alternative interface that accepts well-typed geojson (see play-geojson, but also see https://github.com/jroper/play-geojson/issues/12 ).

Fixed in 47e04f203ed9e40740546c48dd15af35b122ba89
